# Importing Libraries

In [54]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

# Importing the data

In [66]:
df = pd.read_csv('energydata_complete.csv')

In [67]:
df

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,2016-05-27 17:20:00,100,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,2016-05-27 17:40:00,270,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

# Renaming Columns

In [68]:
column_names = {'T1': 'Temp in kitchen',
                'RH_1': 'Humidity in kitchen',
                'T2': 'Temp in living',
                'RH_2': 'Humidity in living',
                'T3': 'Temp in laundry',
                'RH_3': 'Humidity in laundry',
                'T4': 'Temp in office',
                'RH_4': 'Humidity in office',
                'T5': 'Temp in bathroom',
                'RH_5': 'Humidity in bathroom',
                'T6': 'Temp outside building',
                'RH_6': 'Humidity outside building',
                'T7': 'Temp in ironing',
                'RH_7': 'Humidity in ironing',
                'T8': 'Temp in teenager',
                'RH_8': 'Humidity in teenager',
                'T9': 'Temp in parents',
                'RH_9': 'Humidity in parents',
                'T_out': 'Temperature outside',
                'Press_mm_hg': 'Pressure',
                'RH_out': 'Humidity outside',
                'Windspeed': 'Windspeed',
                'Visibility': 'Visibility',
                'Tdewpoint': 'Tdewpoint', 
                'rv1': 'random var1',
                'rv2': 'random var2'
               }

In [69]:
column_names

{'T1': 'Temp in kitchen',
 'RH_1': 'Humidity in kitchen',
 'T2': 'Temp in living',
 'RH_2': 'Humidity in living',
 'T3': 'Temp in laundry',
 'RH_3': 'Humidity in laundry',
 'T4': 'Temp in office',
 'RH_4': 'Humidity in office',
 'T5': 'Temp in bathroom',
 'RH_5': 'Humidity in bathroom',
 'T6': 'Temp outside building',
 'RH_6': 'Humidity outside building',
 'T7': 'Temp in ironing',
 'RH_7': 'Humidity in ironing',
 'T8': 'Temp in teenager',
 'RH_8': 'Humidity in teenager',
 'T9': 'Temp in parents',
 'RH_9': 'Humidity in parents',
 'T_out': 'Temperature outside',
 'Press_mm_hg': 'Pressure',
 'RH_out': 'Humidity outside',
 'Windspeed': 'Windspeed',
 'Visibility': 'Visibility',
 'Tdewpoint': 'Tdewpoint',
 'rv1': 'random var1',
 'rv2': 'random var2'}

In [76]:
df = df.rename(columns=column_names)

In [77]:
df

,date,Appliances,lights,Temp in kitchen,Humidity in kitchen,Temp in living,Humidity in living,Temp in laundry,Humidity in laundry,Temp in office,...,Temp in parents,Humidity in parents,Temperature outside,Pressure,Humidity outside,Windspeed,Visibility,Tdewpoint,random var1,random var2
0,2016-01-11 17:00:00,60,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,2016-05-27 17:20:00,100,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,2016-05-27 17:40:00,270,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [110]:
from sklearn.metrics import r2_score

ValueError: Found input variables with inconsistent numbers of samples: [14, 21]

In [72]:
df_corr = df.corr().round(2)
df_corr

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
Appliances,1.00,0.20,0.06,0.09,0.12,-0.06,0.09,0.04,0.04,0.02,...,0.01,-0.05,0.10,-0.03,-0.15,0.09,0.00,0.02,-0.01,-0.01
lights,0.20,1.00,-0.02,0.11,-0.01,0.05,-0.10,0.13,-0.01,0.11,...,-0.16,-0.01,-0.07,-0.01,0.07,0.06,0.02,-0.04,0.00,0.00
T1,0.06,-0.02,1.00,0.16,0.84,-0.00,0.89,-0.03,0.88,0.10,...,0.84,0.07,0.68,-0.15,-0.35,-0.09,-0.08,0.57,-0.01,-0.01
RH_1,0.09,0.11,0.16,1.00,0.27,0.80,0.25,0.84,0.11,0.88,...,0.12,0.76,0.34,-0.29,0.27,0.20,-0.02,0.64,-0.00,-0.00
T2,0.12,-0.01,0.84,0.27,1.00,-0.17,0.74,0.12,0.76,0.23,...,0.68,0.16,0.79,-0.13,-0.51,0.05,-0.07,0.58,-0.01,-0.01
RH_2,-0.06,0.05,-0.00,0.80,-0.17,1.00,0.14,0.68,-0.05,0.72,...,0.05,0.68,0.03,-0.26,0.58,0.07,-0.01,0.50,0.01,0.01
T3,0.09,-0.10,0.89,0.25,0.74,0.14,1.00,-0.01,0.85,0.12,...,0.90,0.13,0.70,-0.19,-0.28,-0.10,-0.10,0.65,-0.01,-0.01
RH_3,0.04,0.13,-0.03,0.84,0.12,0.68,-0.01,1.00,-0.14,0.90,...,-0.20,0.83,0.12,-0.23,0.36,0.26,0.02,0.41,-0.00,-0.00
T4,0.04,-0.01,0.88,0.11,0.76,-0.05,0.85,-0.14,1.00,-0.05,...,0.89,-0.03,0.66,-0.08,-0.39,-0.19,-0.10,0.52,-0.00,-0.00
RH_4,0.02,0.11,0.10,0.88,0.23,0.72,0.12,0.90,-0.05,1.00,...,-0.04,0.86,0.29,-0.25,0.34,0.30,0.00,0.62,-0.00,-0.00
T5,0.02,-0.08,0.89,0.21,0.72,0.11,0.89,-0.05,0.87,0.09,...,0.91,0.07,0.65,-0.17,-0.27,-0.15,-0.08,0.59,-0.01,-0.01
RH_5,0.01,0.14,-0.01,0.30,0.03,0.25,-0.07,0.38,-0.08,0.35,...,-0.14,0.27,-0.05,-0.12,0.19,0.08,-0.01,0.08,-0.01,-0.01
T6,0.12,-0.08,0.65,0.32,0.80,-0.01,0.69,0.08,0.65,0.26,...,0.67,0.18,0.97,-0.14,-0.57,0.17,-0.08,0.76,-0.02,-0.02
RH_6,-0.08,0.15,-0.62,0.25,-0.58,0.39,-0.65,0.51,-0.70,0.39,...,-0.74,0.39,-0.64,-0.07,0.72,0.10,0.11,-0.26,0.01,0.01
T7,0.03,-0.14,0.84,0.02,0.66,-0.05,0.85,-0.25,0.88,-0.13,...,0.94,-0.08,0.63,-0.10,-0.41,-0.19,-0.11,0.47,-0.00,-0.00
RH_7,-0.06,0.04,0.14,0.80,0.23,0.69,0.17,0.83,0.04,0.89,...,0.03,0.86,0.29,-0.27,0.38,0.21,-0.01,0.64,0.00,0.00
T8,0.04,-0.07,0.83,-0.03,0.58,-0.04,0.80,-0.28,0.80,-0.17,...,0.87,-0.16,0.50,-0.16,-0.30,-0.22,-0.06,0.39,-0.00,-0.00
RH_8,-0.09,0.01,-0.01,0.74,0.07,0.68,0.04,0.83,-0.10,0.85,...,-0.11,0.86,0.12,-0.23,0.49,0.20,0.05,0.50,0.00,0.00
T9,0.01,-0.16,0.84,0.12,0.68,0.05,0.90,-0.20,0.89,-0.04,...,1.00,-0.01,0.67,-0.16,-0.32,-0.18,-0.10,0.58,-0.00,-0.00
RH_9,-0.05,-0.01,0.07,0.76,0.16,0.68,0.13,0.83,-0.03,0.86,...,-0.01,1.00,0.22,-0.18,0.36,0.24,0.01,0.54,-0.00,-0.00
T_out,0.10,-0.07,0.68,0.34,0.79,0.03,0.70,0.12,0.66,0.29,...,0.67,0.22,1.00,-0.14,-0.57,0.19,-0.08,0.79,-0.02,-0.02
Press_mm_hg,-0.03,-0.01,-0.15,-0.29,-0.13,-0.26,-0.19,-0.23,-0.08,-0.25,...,-0.16,-0.18,-0.14,1.00,-0.09,-0.24,0.04,-0.24,0.00,0.00
RH_out,-0.15,0.07,-0.35,0.27,-0.51,0.58,-0.28,0.36,-0.39,0.34,...,-0.32,0.36,-0.57,-0.09,1.00,-0.18,0.08,0.04,0.02,0.02
Windspeed,0.09,0.06,-0.09,0.20,0.05,0.07,-0.10,0.26,-0.19,0.30,...,-0.18,0.24,0.19,-0.24,-0.18,1.00,-0.01,0.13,-0.01,-0.01
Visibility,0.00,0.02,-0.08,-0.02,-0.07,-0.01,-0.10,0.02,-0.10,0.00,...,-0.10,0.01,-0.08,0.04,0.08,-0.01,1.00,-0.04,-0.01,-0.01
Tdewpoint,0.02,-0.04,0.57,0.64,0.58,0.50,0.65,0.41,0.52,0.62,...,0.58,0.54,0.79,-0.24,0.04,0.13,-0.04,1.00,-0.00,-0.00
rv1,-0.01,0.00,-0.01,-0.00,-0.01,0.01,-0.01,-0.00,-0.00,-0.00,...,-0.00,-0.00,-0.02,0.00,0.02,-0.01,-0.01,-0.00,1.00,1.00
rv2,-0.01,0.00,-0.01,-0.00,-0.01,0.01,-0.01,-0.00,-0.00,-0.00,...,-0.00,-0.00,-0.02,0.00,0.02,-0.01,-0.01,-0.00,1.00,1.00

In [113]:
df_drop = df.drop(columns=['date', 'lights'])
df_drop

,Appliances,Temp in kitchen,Humidity in kitchen,Temp in living,Humidity in living,Temp in laundry,Humidity in laundry,Temp in office,Humidity in office,Temp in bathroom,...,Temp in parents,Humidity in parents,Temperature outside,Pressure,Humidity outside,Windspeed,Visibility,Tdewpoint,random var1,random var2
0,60,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,60,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,50,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,50,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,60,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,100,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,23.200000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,90,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,23.230000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,270,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,23.230000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,420,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,23.200000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,430,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,23.200000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [114]:
from sklearn.metrics import r2_score

In [118]:
temp_in_living = df['Temp in living']

In [119]:
temp_outside_building = df['Temp outside building']
temp_outside_building

0         7.026667
1         6.833333
2         6.560000
3         6.433333
4         6.366667
           ...
19730    24.796667
19731    24.196667
19732    23.626667
19733    22.433333
19734    21.026667
Name: Temp outside building, Length: 19735, dtype: float64

In [121]:
r2_score = r2_score(temp_in_living, temp_outside_building)
r2_score

-35.393237547324794

# Normalizing the dataset

In [61]:
from sklearn.preprocessing import MinMaxScaler

In [62]:
scaler = MinMaxScaler()

In [81]:
df_norm = pd.DataFrame(scaler.fit_transform(df_drop), columns=df_drop.columns)

In [82]:
df_norm

,Appliances,Temp in kitchen,Humidity in kitchen,Temp in living,Humidity in living,Temp in laundry,Humidity in laundry,Temp in office,Humidity in office,Temp in bathroom,...,Temp in parents,Humidity in parents,Temperature outside,Pressure,Humidity outside,Windspeed,Visibility,Tdewpoint,random var1,random var2
0,0.046729,0.327350,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.327350,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.327350,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.327350,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.327350,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,0.084112,0.926786,0.537657,0.711655,0.606309,0.830841,0.579374,0.864865,0.765258,0.752031,...,0.864724,0.729443,0.891747,0.602326,0.416667,0.238095,0.348718,0.901961,0.861981,0.861981
19731,0.074766,0.919747,0.536006,0.701769,0.607836,0.825302,0.582178,0.864865,0.765258,0.754897,...,0.864724,0.729443,0.887460,0.602326,0.421053,0.250000,0.361538,0.900452,0.985726,0.985726
19732,0.242991,0.919747,0.538666,0.692651,0.627198,0.818378,0.603988,0.864865,0.771233,0.754897,...,0.864724,0.729443,0.883173,0.602326,0.425439,0.261905,0.374359,0.898944,0.583979,0.583979
19733,0.383178,0.919747,0.549491,0.677054,0.634717,0.805085,0.585294,0.864865,0.773794,0.752031,...,0.864724,0.730581,0.878885,0.602326,0.429825,0.273810,0.387179,0.897436,0.126371,0.126371
19734,0.392523,0.919747,0.538758,0.666171,0.632902,0.799546,0.579062,0.864865,0.781192,0.752031,...,0.864724,0.731719,0.874598,0.602326,0.434211,0.285714,0.400000,0.895928,0.682391,0.682391

In [83]:
df_features = df_norm.drop(columns=['Appliances'])
df_features

,Temp in kitchen,Humidity in kitchen,Temp in living,Humidity in living,Temp in laundry,Humidity in laundry,Temp in office,Humidity in office,Temp in bathroom,Humidity in bathroom,...,Temp in parents,Humidity in parents,Temperature outside,Pressure,Humidity outside,Windspeed,Visibility,Tdewpoint,random var1,random var2
0,0.327350,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,0.381691,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.327350,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,0.381691,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.327350,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,0.380037,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.327350,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,0.380037,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.327350,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,0.380037,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,0.926786,0.537657,0.711655,0.606309,0.830841,0.579374,0.864865,0.765258,0.752031,0.339590,...,0.864724,0.729443,0.891747,0.602326,0.416667,0.238095,0.348718,0.901961,0.861981,0.861981
19731,0.919747,0.536006,0.701769,0.607836,0.825302,0.582178,0.864865,0.765258,0.754897,0.338487,...,0.864724,0.729443,0.887460,0.602326,0.421053,0.250000,0.361538,0.900452,0.985726,0.985726
19732,0.919747,0.538666,0.692651,0.627198,0.818378,0.603988,0.864865,0.771233,0.754897,0.337585,...,0.864724,0.729443,0.883173,0.602326,0.425439,0.261905,0.374359,0.898944,0.583979,0.583979
19733,0.919747,0.549491,0.677054,0.634717,0.805085,0.585294,0.864865,0.773794,0.752031,0.336583,...,0.864724,0.730581,0.878885,0.602326,0.429825,0.273810,0.387179,0.897436,0.126371,0.126371
19734,0.919747,0.538758,0.666171,0.632902,0.799546,0.579062,0.864865,0.781192,0.752031,0.336583,...,0.864724,0.731719,0.874598,0.602326,0.434211,0.285714,0.400000,0.895928,0.682391,0.682391

In [84]:
target = df_norm['Appliances']
target

0        0.046729
1        0.046729
2        0.037383
3        0.037383
4        0.046729
           ...
19730    0.084112
19731    0.074766
19732    0.242991
19733    0.383178
19734    0.392523
Name: Appliances, Length: 19735, dtype: float64

In [85]:
from sklearn.model_selection import train_test_split

In [86]:
x_train, x_test, y_train, y_test = train_test_split(df_features, target, test_size=0.3, random_state=42)

In [87]:
x_train

,Temp in kitchen,Humidity in kitchen,Temp in living,Humidity in living,Temp in laundry,Humidity in laundry,Temp in office,Humidity in office,Temp in bathroom,Humidity in bathroom,...,Temp in parents,Humidity in parents,Temperature outside,Pressure,Humidity outside,Windspeed,Visibility,Tdewpoint,random var1,random var2
9129,0.497360,0.236767,0.122850,0.565939,0.373878,0.303474,0.476577,0.264760,0.408027,0.159533,...,0.475893,0.376380,0.168810,0.862791,0.776316,0.142857,0.984615,0.192308,0.724554,0.724554
2453,0.286167,0.482616,0.188999,0.669978,0.217957,0.735317,0.270270,0.691421,0.178691,0.333576,...,0.240375,0.703504,0.262594,0.836434,0.807018,0.142857,0.600000,0.342383,0.864041,0.864041
9152,0.422386,0.230529,0.057427,0.606430,0.373878,0.338059,0.414414,0.236449,0.378404,0.151639,...,0.468262,0.409803,0.110397,0.853488,0.859649,0.095238,0.917949,0.158371,0.499502,0.499502
12694,0.560718,0.446840,0.280834,0.704002,0.514290,0.515189,0.540541,0.486556,0.509317,0.424604,...,0.561915,0.340784,0.444802,0.559690,0.750000,0.119048,0.384615,0.558069,0.323173,0.323173
16952,0.835269,0.422071,1.000000,0.318493,0.745383,0.459106,0.900901,0.516432,0.748845,0.455819,...,0.854318,0.633278,0.849946,0.530233,0.355263,0.142857,0.600000,0.787330,0.341060,0.341060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,0.524815,0.381892,0.239157,0.636236,0.481888,0.478268,0.576577,0.517712,0.455805,0.250877,...,0.568852,0.471578,0.468382,0.492248,0.706140,0.476190,0.600000,0.562594,0.910318,0.910318
11964,0.591341,0.458949,0.428883,0.607461,0.456962,0.582489,0.557658,0.702518,0.417582,0.285310,...,0.561915,0.625966,0.717042,0.469767,0.552632,0.142857,0.600000,0.791855,0.698711,0.698711
5390,0.369588,0.238785,0.152653,0.481582,0.240944,0.412370,0.279279,0.325651,0.302914,0.161743,...,0.312175,0.426325,0.126474,0.595349,0.828947,0.261905,0.948718,0.165913,0.381388,0.381388
860,0.527983,0.234933,0.315047,0.412016,0.332336,0.380122,0.540541,0.341585,0.259914,0.245539,...,0.375650,0.509106,0.227224,0.831008,0.530702,0.095238,0.600000,0.114630,0.020909,0.020909
15795,0.478705,0.294652,0.275503,0.509045,0.456962,0.365633,0.414414,0.502490,0.369804,0.192086,...,0.468262,0.500828,0.374598,0.682558,0.809211,0.071429,0.600000,0.495475,0.349076,0.349076

In [88]:
y_train

9129     0.037383
2453     0.018692
9152     0.028037
12694    0.102804
16952    0.037383
           ...
11284    0.046729
11964    0.102804
5390     0.018692
860      0.065421
15795    0.112150
Name: Appliances, Length: 13814, dtype: float64

In [89]:
x_test

,Temp in kitchen,Humidity in kitchen,Temp in living,Humidity in living,Temp in laundry,Humidity in laundry,Temp in office,Humidity in office,Temp in bathroom,Humidity in bathroom,...,Temp in parents,Humidity in parents,Temperature outside,Pressure,Humidity outside,Windspeed,Visibility,Tdewpoint,random var1,random var2
8980,0.432946,0.230529,0.120669,0.525822,0.256730,0.380122,0.419820,0.279129,0.312470,0.322900,...,0.457856,0.408251,0.217578,0.920930,0.846491,0.166667,0.953846,0.298643,0.512428,0.512428
2754,0.538543,0.717641,0.377272,0.700066,0.368339,0.956224,0.489489,0.567933,0.224346,0.426866,...,0.145682,0.622241,0.247588,0.588372,0.868421,0.214286,0.400000,0.352941,0.469466,0.469466
9132,0.485744,0.233281,0.111461,0.564252,0.371109,0.300670,0.467568,0.260350,0.408027,0.157503,...,0.468262,0.377621,0.167203,0.858140,0.776316,0.142857,0.984615,0.190045,0.002761,0.002761
14359,0.485744,0.385561,0.566271,0.404255,0.401573,0.381679,0.656757,0.323346,0.411212,0.202260,...,0.561915,0.388797,0.445338,0.895349,0.616228,0.369048,0.600000,0.466817,0.205799,0.205799
8875,0.335093,0.223007,0.026411,0.552910,0.232635,0.356753,0.374775,0.311851,0.244625,0.288467,...,0.427680,0.477373,0.145766,0.938372,0.912281,0.285714,0.735897,0.233032,0.215015,0.215015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,0.560718,0.300248,0.370487,0.412504,0.386895,0.576414,0.608709,0.488263,0.264692,0.304506,...,0.312175,0.507726,0.220257,0.841860,0.756579,0.107143,0.430769,0.251131,0.910115,0.910115
10993,0.518479,0.310063,0.225345,0.593214,0.481888,0.446799,0.464865,0.495092,0.446249,0.264410,...,0.561915,0.528422,0.439443,0.422093,0.651316,0.583333,0.600000,0.486425,0.975531,0.975531
11761,0.436818,0.340611,0.188999,0.633705,0.381356,0.403490,0.422523,0.453692,0.378404,0.230779,...,0.490114,0.356926,0.392283,0.665504,0.796053,0.083333,0.969231,0.515083,0.792703,0.792703
12364,0.550158,0.390973,0.334383,0.602774,0.481888,0.468453,0.576577,0.554702,0.503583,0.237746,...,0.620881,0.417770,0.494105,0.545736,0.596491,0.642857,0.600000,0.520362,0.608307,0.608307
11863,0.432946,0.420145,0.213230,0.688912,0.365570,0.482474,0.414414,0.589273,0.378404,0.243810,...,0.479709,0.507726,0.583065,0.530620,0.734649,0.500000,0.505128,0.740573,0.198911,0.198911

In [90]:
y_test

8980     0.028037
2754     0.074766
9132     0.037383
14359    0.037383
8875     0.056075
           ...
831      0.224299
10993    0.046729
11761    0.037383
12364    0.093458
11863    0.037383
Name: Appliances, Length: 5921, dtype: float64

In [91]:
from sklearn.linear_model import LinearRegression

In [92]:
linear_model = LinearRegression()

In [93]:
linear_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [94]:
predicted_values = linear_model.predict(x_test)

In [95]:
from sklearn.metrics import mean_absolute_error

In [97]:
mae = mean_absolute_error(y_test, predicted_values)

In [98]:
mae.round(2)

0.05

In [99]:
rss = np.sum(np.square(y_test - predicted_values))

In [101]:
rss.round(2)

45.35

In [102]:
from sklearn.metrics import mean_squared_error

In [103]:
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))

In [108]:
rmse.round(3)

0.088

In [105]:
from sklearn.metrics import r2_score

In [106]:
r2_score = r2_score(y_test, predicted_values)

In [107]:
r2_score.round(2)

0.15

In [117]:
r2_score = r2_score(Temp in living, Temp outside building)
r2_score

SyntaxError: invalid syntax (<ipython-input-117-392e64071d91>, line 1)

In [130]:

#comparing the effects of regularisation
def get_weights_df(linear_model, feat, col_name):
  #this function returns the weight of every feature
  weights = pd.Series(linear_model.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

linear_model_weights = get_weights_df(linear_model, x_train, 'Linear_Model_Weight')
ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge_Weight')
lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')

final_weights = pd.merge(linear_model_weights, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on='Features')

In [127]:

from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)

Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [129]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.5)
ridge_reg.fit(x_train, y_train)

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [131]:
final_weights

                     Features  Linear_Model_Weight  Ridge_Weight  Lasso_weight
0          Humidity in living            -0.456698     -0.401134     -0.000000
1         Temperature outside            -0.321860     -0.250765      0.000000
2              Temp in living            -0.236178     -0.193880      0.000000
3             Temp in parents            -0.189941     -0.188584     -0.000000
4        Humidity in teenager            -0.157595     -0.156596     -0.000110
5            Humidity outside            -0.077671     -0.050541     -0.049557
6         Humidity in ironing            -0.044614     -0.046291     -0.000000
7         Humidity in parents            -0.039800     -0.041701     -0.000000
8            Temp in bathroom            -0.015657     -0.020727     -0.000000
9             Temp in kitchen            -0.003281     -0.021549      0.000000
10                random var1             0.000770      0.000743     -0.000000
11                random var2             0.000770      0.000743     -0.000000
12                   Pressure             0.006839      0.006516     -0.000000
13            Temp in ironing             0.010319      0.010021     -0.000000
14                 Visibility             0.012307      0.012032      0.000000
15       Humidity in bathroom             0.016006      0.016176      0.000000
16         Humidity in office             0.026386      0.024168      0.000000
17             Temp in office             0.028981      0.027006     -0.000000
18                  Windspeed             0.029183      0.030463      0.002912
19  Humidity outside building             0.038049      0.035023     -0.000000
20        Humidity in laundry             0.096048      0.094976      0.000000
21           Temp in teenager             0.101995      0.100754      0.000000
22                  Tdewpoint             0.117758      0.076668      0.000000
23      Temp outside building             0.236425      0.213316      0.000000
24            Temp in laundry             0.290627      0.287408      0.000000
25        Humidity in kitchen             0.553547      0.511932      0.017880

In [135]:
weight_df

NameError: name 'weight_df' is not defined

In [136]:
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))

In [137]:
rmse.round(3)

0.088